#!/bin/bash
# mounter for windows and ubuntu partitions

if [ "`mount | grep Windows`" == "" ]; then
( sudo mount /dev/sda2 /media/Windows && sleep 1 ) &
fi
if [ "`mount | grep Ubuntu`" == "" ]; then
( sudo mount /dev/sda6 /media/Ubuntu && sleep 1 ) &
fi
