#!/bin/sh
# xinitrc.d {{{
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi
# }}}
# .Xresources {{{
if [ -f ~/.Xresources ]; then
  xrdb -merge ~/.Xresources &
fi
# }}}
# case statement {{{
case "$1" in

awesome|*)
exec awesome
;;

esac
# }}}
