#!/bin/bash

site="https://github.com/libimobiledevice"
sources=""

sources="libimobiledevice"
if [ ! -d ./$sources ]; then
  git clone $site/$sources
else 
    cd $sources
    git pull; echo "$sources updated";
    cd ..
fi

sources="usbmuxd"
if [ ! -d ./$sources ]; then
  git clone $site/$sources.git
else
    cd $sources
    git pull; echo "$sources updated";
    cd ..
fi

sources="libplist"
if [ ! -d ./$sources ]; then
  git clone $site/$sources
else
  cd $sources
  git pull; echo "$sources updated";
  cd ..
fi

sources="libirecovery"
if [ ! -d ./$sources ]; then
  git clone $site/$sources
else
  cd $sources
  git pull; echo "$sources updated";
  cd ..
fi

sources="sbmanager"
if [ ! -d ./$sources ]; then
  git clone $site/$sources
else
  cd $sources
  git pull; echo "$sources updated";
  cd ..
fi

sources="ideviceinstaller"
if [ ! -d ./$sources ]; then
  git clone $site/$sources
else
  cd $sources
  git pull; echo "$sources updated";
  cd ..
fi

sources="ifuse"
if [ ! -d ./$sources ]; then
  git clone $site/$sources
else
  cd $sources
  git pull; echo "$sources updated";
  cd ..
fi
exit 0

