#!/bin/bash

usage () {
echo "$0 website_url"
echo "examples
echo "getallweb http://www.stupidsite.com/restrictedplace.html"
exit 0
}

if [[ $1 == "" ]]; then
usage
else
wget -r -p -U Mozilla --limit-rate= --wait=20 $1
fi


