#!/bin/bash

if [[ $1 == "" ]]; then
  echo "Usage:"
  echo "$0 <running process>"
  echo "Kills with sudo killall"
fi

if [[ $1 != "" ]]; then
  sudo killall $1;
  echo "Attempted to kill $1"
fi

exit 0
